#
#        ________           __  _         __  ___        __                   ___    ____  ____
#      / ____/ /___ ______/ /_(_)____   /  |/  /____   / /   ____  ____ _   /   |  / __ \/  _/
#     / __/ / / __ `/ ___/ __/ / ___/  / /|_/ / ___/  / /   / __ \/ __ `/  / /| | / /_/ // /
#    / /___/ / /_/ (__  ) /_/ / /__   / /  / / /__   / /___/ /_/ / /_/ /  / ___ |/ ____// /
#   /_____/_/\__,_/____/\__/_/\___/  /_/  /_/\___/  /_____/\____/\__, /  /_/  |_/_/   /___/
#                                                               /____/
#

# ElasticSearch server configuration
elasticsearch:
  hostname: "localhost"
  port: 9200
  username: "elastic"
  password: "changeme"
#

# Configs
config:
  base-index-name: "mc-log"
  pool-delay: 200
#